blueprint:
  name: Dev Test Jeff
  description: >
    Testing testing testing.

  domain: automation
  input:
    notify_device:
      name: Devices to notify
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    trigger_entity:
      name: Trigger entity
      description: Send the notification when this boolean turns on
      selector:
        entity:
          multiple: true
          filter:
            - integration: reolink
              domain: binary_sensor

mode: restart
max_exceeded: silent

variables:
  notify_device: !input notify_device
  trigger_entity: !input trigger_entity

trigger:
  - platform: time_pattern
    minutes: "/5"

action:
  - condition: or
    conditions:
      - "{{ trigger_entity | map('states') | list }}"
